### PR TITLE
Add examples to metadata and update with package

### PR DESCRIPTION
**Pull request by thomcsmits**
- Add examples to metadata of templates
- Change datatypes to assay_display_name
- Import common functions from hubmap_template_helper package

### CODE REVIEW

**Review by john-conroy — COMMENTED** [review]
Looks good to me. Which changes warrant updates to the `last_modified_unix_timestamp`?

**Review by Chris-Csonka — APPROVED** [review]
I read through all the updates, looks good to me, too.

**Comment by jpuerto-psc** [comment]
> Looks good to me. Which changes warrant updates to the `last_modified_unix_timestamp`?

I think functional changes would warrant an update. Not sure that metadata updates should trigger that.

**Comment by thomcsmits** [comment]
> > Looks good to me. Which changes warrant updates to the `last_modified_unix_timestamp`?
> 
> I think functional changes would warrant an update. Not sure that metadata updates should trigger that.

Sounds logical to me

**Pull request merged**
